###################################
############DEPENDECIES############
###################################
 library(dplyr)

###################################
############FUNCTIONS##############
###################################


get_angle_and_scale_qctab_new <- function(x, paramtab, centre_f){
  image_file <- paramtab[[x,1]]
  fovea_height <- paramtab[[x,5]]
  model <- run_generate_model_and_find_fovea_dip_poisition(image_file)
  e <- registar(image_file, debug = FALSE)
  amodel <- center_align(model, centre_f)
  smoothed_ellipse1 <- smooth_ellipse_max_slope(e, 31)
  smoothed_ellipse2 <- smooth_ellipse_plateu(e, 31)
  rotate_val1 <- new_find_rotate(smoothed_ellipse1)
  rotate_val2 <- new_find_rotate(smoothed_ellipse2)
  d1 <- dim(amodel)[1]*(1/3)
  fovea_height_scale <- fovea_height*dim(amodel)[1]
  scale_co <- d1/fovea_height_scale
  return(data.frame(image_file = image_file, rotate_val1 = rotate_val1, rotate_val2 = rotate_val2, scale_co = scale_co))
}



#function to test if the center align function and the fit centred surface function will work and which files to therefore not use
test_both <- function(image_file){
  model <- run_generate_model_and_find_fovea_dip_poisition(image_file)
  debug=FALSE
  if (abs(0.5 - c(model$zcenter)/dim(model$model$top_band)[1]) > 
      0.15) {
    model$zcenter = dim(model$model$top_band)[1]/2
  }
  if (abs(0.5 - c(model$ycenter)/dim(model$model$top_band)[2]) > 
      0.15) {
    model$ycenter = dim(model$model$top_band)[2]/2
  }
  centered_band = center_and_square(model)
  v360 = extract_circle_params(centered_band)
  divs = do.call(rbind, lapply(lapply(v360$s.ss, fit_deriv, debug), unlist))
  if(dim(divs)[1]==360){
    band_test =1
    e <- registar(image_file, debug=FALSE)
    f= centre_f
    model$ycenter = fit_deriv(model$model$top_band[model$zcenter,])$midpoint
    model$zcenter = fit_deriv(model$model$top_band[, model$ycenter])$midpoint
    centers = (dim(model$model$top_band)/2) - c(model$zcenter, model$ycenter)
    rangs = list()
    for (x in 1:length(centers)) {
      if (centers[x] < 0) {
        r = abs(centers[x] * 2):dim(model$model$top_band)[x]
      }
      else {
        r = 1:(dim(model$model$top_band)[x] - centers[x] * 2)
      }
      rangs[[x]] = r
    }
    ns = dim(model$model$top_band) * f
    centered_band = model$model$top_band[rangs[[1]], rangs[[2]]]
    ndata = NULL
    ds = dim(centered_band)
    st = ns/2
    
    #ndata = top_band_surface[((ds[1]/2) - st[1]):((ds[1]/2) + st[1]), ((ds[2]/2) - st[2]):((ds[2]/2) + st[2])]
    
    if((((ds[1]/2) - st[1])<0)||(((ds[1]/2)<0)||(((ds[2]/2) - st[2])<0)||(((ds[2]/2) + st[2])<0))){
      align_test = 0
    } else {
      align_test = 1
    }
  } else {
    band_test = 0
    align_test = 0
  }
  return <- data.frame(align_test, band_test)
}

select_scans_qc <- function(x, runs2remain, comp_table){
  tmp <- comp_table[[x]]
  tmp_new <- tmp[runs2remain,]
} 

###################################
###############DATA################
###################################

centre_f = 0.8

######reads stored data generated by lower down scripts
odds_rotate_and_scale_df <- readRDS("/Users/currant/OCTeyes/evens_rotate_and_scale_dataframe20170607")
evens_rotate_and_scale_df <- readRDS("/Users/currant/OCTeyes/evens_rotate_and_scale_dataframe20170607")


######full lists of output for pruning########
odds_minus <- readRDS("/Users/currant/OCTeyes/R_objects/R_comp_objects_final/odds_fix_final20170518")
evens_minus <- readRDS("/Users/currant/OCTeyes/R_objects/R_comp_objects_final/evens_fix_final20170518")
odds_scale <- readRDS("/Users/currant/OCTeyes/R_objects/R_comp_objects_final/odds_scale_fix_final20170518")
evens_scale <- readRDS("/Users/currant/OCTeyes/R_objects/R_comp_objects_final/evens_scale_fix_final20170518")
odds_rotate <- readRDS("/Users/currant/OCTeyes/R_objects/R_comp_objects_final/odds_rotate_fix_final20170518")
evens_rotate <- readRDS("/Users/currant/OCTeyes/R_objects/R_comp_objects_final/evens_rotate_fix_final20170518")
odds_tesselate <- readRDS("/Users/currant/OCTeyes/R_objects/R_comp_objects_final/odds_tesselate_fix_final20170518")
evens_tesselate <- readRDS("/Users/currant/OCTeyes/R_objects/R_comp_objects_final/evens_tesselate_fix_final20170518")



###################################
#############ANALYSIS##############
###################################

############Genertae tables of rtate and scaling factors ready for quality control##############
odds_rotate_and_scale_dataframe <- lapply(1:dim(all_params_odd_minus)[1], get_angle_and_scale_qctab, paramtab=all_params_odd_minus, centre_f=centre_f)
odds_rotate_and_scale_dataframe <- do.call(rbind, odds_rotate_and_scale_table)
saveRDS(odds_rotate_and_scale_dataframe, paste("/Users/currant/OCTeyes/odds_rotate_and_scale_dataframe",  strftime(Sys.time(), "%Y%m%d"), sep=""))
odds_rotate_and_scale_dataframe <- readRDS("/Users/currant/OCTeyes/odds_rotate_and_scale_dataframe20170607")

evens_rotate_and_scale_dataframe <- lapply(1:dim(all_params_even_minus)[1], get_angle_and_scale_qctab, paramtab = all_params_even_minus, centre_f = centre_f)
evens_rotate_and_scale_dataframe <- do.call(rbind, evens_rotate_and_scale_dataframe)
saveRDS(evens_rotate_and_scale_dataframe, paste("/Users/currant/OCTeyes/evens_rotate_and_scale_dataframe",  strftime(Sys.time(), "%Y%m%d"), sep=""))
evens_rotate_and_scale_dataframe <- read.table("/Users/currant/OCTeyes/evens_rotate_and_scale_dataframe20170607")

############Genertae tables of rtate and scaling factors ready for quality control##############
odds_rotate_and_scale_dataframe_new <- lapply(1:dim(all_params_odd_minus)[1], get_angle_and_scale_qctab_new, paramtab=all_params_odd_minus, centre_f=centre_f)
odds_rotate_and_scale_dataframe_new <- do.call(rbind, odds_rotate_and_scale_dataframe_new)
saveRDS(odds_rotate_and_scale_dataframe_new, paste("/Users/currant/OCTeyes/odds_rotate_and_scale_dataframe_new",  strftime(Sys.time(), "%Y%m%d"), sep=""))
odds_rotate_and_scale_dataframe_new <- readRDS("/Users/currant/OCTeyes/odds_rotate_and_scale_dataframe_new20170619")
odds_rotate_and_scale_dataframe_new$mean_rotate <- (odds_rotate_and_scale_dataframe_new$rotate_val1 + odds_rotate_and_scale_dataframe_new$rotate_val2)/2
odds_rotate_and_scale_dataframe_new$rotate_diff <- abs(odds_rotate_and_scale_dataframe_new$rotate_val2 - odds_rotate_and_scale_dataframe_new$rotate_val1)

evens_rotate_and_scale_dataframe_new <- lapply(1:dim(all_params_even_minus)[1], get_angle_and_scale_qctab_new, paramtab = all_params_even_minus, centre_f = centre_f)
evens_rotate_and_scale_dataframe_new <- do.call(rbind, evens_rotate_and_scale_dataframe_new)
saveRDS(evens_rotate_and_scale_dataframe_new, paste("/Users/currant/OCTeyes/evens_rotate_and_scale_dataframe_new",  strftime(Sys.time(), "%Y%m%d"), sep=""))
evens_rotate_and_scale_dataframe_new <- readRDS("/Users/currant/OCTeyes/evens_rotate_and_scale_dataframe_new20170619")
evens_rotate_and_scale_dataframe_new$mean_rotate <- (evens_rotate_and_scale_dataframe_new$rotate_val1 + evens_rotate_and_scale_dataframe_new$rotate_val2)/2
evens_rotate_and_scale_dataframe_new$rotate_diff <- abs(evens_rotate_and_scale_dataframe_new$rotate_val2 - evens_rotate_and_scale_dataframe_new$rotate_val1)

#############Filters out any samples that don't meet the scale and rotate quality control measures - currently a rotation of more than an absolute value of 20, and a scaling of more than ±0.2##################
#######Filters just by angle##################
angle_corrected_odds <- filter(odds_rotate_and_scale_dataframe, abs(rotate_val) < 20)
angle_corrected_odds_ids <- which(abs(odds_rotate_and_scale_dataframe$rotate_val) < 20)
angle_corrected_evens <- filter(evens_rotate_and_scale_dataframe, abs(rotate_val) < 20)
angle_corrected_evens_ids <- which(abs(evens_rotate_and_scale_dataframe$rotate_val) < 20)
print("The percentage of odd samples that passed the angle quality control is:")
print((dim(angle_corrected_odds)[1]/dim(odds_rotate_and_scale_dataframe)[1])*100)
print("The percentage of even samples that passed the angle quality control is:")
print((dim(angle_corrected_evens)[1]/dim(evens_rotate_and_scale_dataframe)[1])*100)
cross_angle_corrected_ids <- intersect(angle_corrected_odds_ids, angle_corrected_evens_ids)

#######Filters just by scaling factor##########
scale_corrected_odds <- filter(odds_rotate_and_scale_dataframe, scale_co < 1.2 & scale_co > 0.8)
scale_corrected_odds_ids <- which(odds_rotate_and_scale_dataframe$scale_co < 1.2 & odds_rotate_and_scale_dataframe$scale_co > 0.8)
scale_corrected_evens <- filter(evens_rotate_and_scale_dataframe, scale_co < 1.2 & scale_co > 0.8)
scale_corrected_evens_ids <- which(evens_rotate_and_scale_dataframe$scale_co <1.2 & evens_rotate_and_scale_dataframe$scale_co > 0.8)
print("The percentage of odd samples that passed the scale quality control is:")
print((dim(scale_corrected_odds)[1]/dim(odds_rotate_and_scale_dataframe)[1])*100)
print("The percentage of even samples that passed the scale quality control is:")
print((dim(scale_corrected_evens)[1]/dim(evens_rotate_and_scale_dataframe)[1])*100)
cross_scale_corrected_ids <- intersect(scale_corrected_odds_ids, scale_corrected_evens_ids)

######Filters by both rotation and scaling factor########
scale_and_angle_corrected_odds <- filter(angle_corrected_odds, scale_co < 1.2 & scale_co > 0.8)
scale_and_angle_corrected_odds_ids <- which((abs(odds_rotate_and_scale_dataframe$rotate_val) < 20) & ((odds_rotate_and_scale_dataframe$scale_co < 1.2 & odds_rotate_and_scale_dataframe$scale_co > 0.8)))
scale_and_angle_corrected_evens <- filter(angle_corrected_evens, scale_co < 1.2 & scale_co > 0.8)
scale_and_angle_corrected_evens_ids <- which((abs(evens_rotate_and_scale_dataframe$rotate_val) < 20) & (evens_rotate_and_scale_dataframe$scale_co <1.2 & evens_rotate_and_scale_dataframe$scale_co > 0.8))
print("The percentage of odd samples that passed angle and scaling quality control is:")
print((dim(scale_and_angle_corrected_odds)[1]/dim(odds_rotate_and_scale_dataframe)[1])*100)
print("The percentage of even samples that passed angle and scaling quality control is:")
print((dim(scale_and_angle_corrected_evens)[1]/dim(evens_rotate_and_scale_dataframe)[1])*100)
cross_joint_corrected_ids <- intersect(scale_and_angle_corrected_odds_ids, scale_and_angle_corrected_evens_ids)


rotate_diff_corrected_odds <- which(odds_rotate_and_scale_dataframe_new$rotate_diff < 20)
rotate_diff_corrected_evens <- which(evens_rotate_and_scale_dataframe_new$rotate_diff < 20)
cross_rotate_diff_corrected <- intersect(rotate_diff_corrected_evens, rotate_diff_corrected_odds)


##########################################################################
##########################################################################
##########################################################################
#Select only cross_angle_corrected_ids from tess_v_tess, all_v_all, scale_v_scale and rotate_v_rotate
angle_qc_tess_v_tess <- lapply(1:length(tess_v_tess), select_scans_qc, cross_angle_corrected_ids, tess_v_tess)
angle_qc_all_v_all <- lapply(1:length(all_v_all), select_scans_qc, cross_angle_corrected_ids, all_v_all)
angle_qc_scale_v_scale <- lapply(1:length(scale_v_scale), select_scans_qc, cross_angle_corrected_ids, scale_v_scale)
angle_qc_rotate_v_rotate <- lapply(1:length(rotate_v_rotate), select_scans_qc, cross_angle_corrected_ids, rotate_v_rotate)

scale_qc_tess_v_tess <- lapply(1:length(tess_v_tess), select_scans_qc, cross_scale_corrected_ids, tess_v_tess)
scale_qc_all_v_all <- lapply(1:length(all_v_all), select_scans_qc, cross_scale_corrected_ids, all_v_all)
scale_qc_scale_v_scale <- lapply(1:length(scale_v_scale), select_scans_qc, cross_scale_corrected_ids, scale_v_scale)
scale_qc_rotate_v_rotate <- lapply(1:length(rotate_v_rotate), select_scans_qc, cross_scale_corrected_ids, rotate_v_rotate)

joint_qc_tess_v_tess <- lapply(1:length(tess_v_tess), select_scans_qc, cross_joint_corrected_ids, tess_v_tess)
joint_qc_all_v_all <- lapply(1:length(all_v_all), select_scans_qc, cross_joint_corrected_ids, all_v_all)
joint_qc_scale_v_scale <- lapply(1:length(scale_v_scale), select_scans_qc, cross_joint_corrected_ids, scale_v_scale)
joint_qc_rotate_v_rotate <- lapply(1:length(rotate_v_rotate), select_scans_qc, cross_joint_corrected_ids, rotate_v_rotate)

rotate_diff_tess_v_tess <- lapply(1:length(tess_v_tess), select_scans_qc, cross_rotate_diff_corrected, tess_v_tess)
rotate_diff_all_v_all <- lapply(1:length(all_v_all), select_scans_qc, cross_rotate_diff_corrected, all_v_all)
rotate_diff_scale_v_scale <- lapply(1:length(scale_v_scale), select_scans_qc, cross_rotate_diff_corrected, scale_v_scale)
rotate_diff_rotate_v_rotate <- lapply(1:length(rotate_v_rotate), select_scans_qc, cross_rotate_diff_corrected, rotate_v_rotate)

#Calculate comparison correlations
angle_qc_tess_v_tess_norm_corr <- lapply((final_min+1):(final_max+1), get_correls, comp_table = angle_qc_tess_v_tess)
angle_qc_tess_v_tess_corr <- do.call(rbind, angle_qc_tess_v_tess_norm_corr)
angle_qc_tess_v_tess_corr$qc_type <- 'angle'
angle_qc_all_v_all_norm_corr <- lapply((final_min+1):(final_max+1), get_correls, comp_table = angle_qc_all_v_all)
angle_qc_all_v_all_corr <- do.call(rbind, angle_qc_all_v_all_norm_corr)
angle_qc_all_v_all_corr$qc_type <- 'angle'
angle_qc_rotate_v_rotate_norm_corr <- lapply((final_min+1):(final_max+1), get_correls, comp_table = angle_qc_rotate_v_rotate)
angle_qc_rotate_v_rotate_corr <- do.call(rbind, angle_qc_rotate_v_rotate_norm_corr)
angle_qc_rotate_v_rotate_corr$qc_type <- 'angle'
angle_qc_scale_v_scale_norm_corr <- lapply((final_min+1):(final_max+1), get_correls, comp_table = angle_qc_scale_v_scale)
angle_qc_scale_v_scale_corr <- do.call(rbind, angle_qc_scale_v_scale_norm_corr)
angle_qc_scale_v_scale_corr$qc_type <- 'angle'

scale_qc_tess_v_tess_norm_corr <- lapply((final_min+1):(final_max+1), get_correls, comp_table = scale_qc_tess_v_tess)
scale_qc_tess_v_tess_corr <- do.call(rbind, scale_qc_tess_v_tess_norm_corr)
scale_qc_tess_v_tess_corr$qc_type <- 'scale'
scale_qc_all_v_all_norm_corr <- lapply((final_min+1):(final_max+1), get_correls, comp_table = scale_qc_all_v_all)
scale_qc_all_v_all_corr <- do.call(rbind, scale_qc_all_v_all_norm_corr)
scale_qc_all_v_all_corr$qc_type <- 'scale'
scale_qc_rotate_v_rotate_norm_corr <- lapply((final_min+1):(final_max+1), get_correls, comp_table = scale_qc_rotate_v_rotate)
scale_qc_rotate_v_rotate_corr <- do.call(rbind, scale_qc_rotate_v_rotate_norm_corr)
scale_qc_rotate_v_rotate_corr$qc_type <- 'scale'
scale_qc_scale_v_scale_norm_corr <- lapply((final_min+1):(final_max+1), get_correls, comp_table = scale_qc_scale_v_scale)
scale_qc_scale_v_scale_corr <- do.call(rbind, scale_qc_scale_v_scale_norm_corr)
scale_qc_scale_v_scale_corr$qc_type <- 'scale'

joint_qc_tess_v_tess_norm_corr <- lapply((final_min+1):(final_max+1), get_correls, comp_table = joint_qc_tess_v_tess)
joint_qc_tess_v_tess_corr <- do.call(rbind, joint_qc_tess_v_tess_norm_corr)
joint_qc_tess_v_tess_corr$qc_type <- 'joint'
joint_qc_all_v_all_norm_corr <- lapply((final_min+1):(final_max+1), get_correls, comp_table = joint_qc_all_v_all)
joint_qc_all_v_all_corr <- do.call(rbind, joint_qc_all_v_all_norm_corr)
joint_qc_all_v_all_corr$qc_type <- 'joint'
joint_qc_rotate_v_rotate_norm_corr <- lapply((final_min+1):(final_max+1), get_correls, comp_table = joint_qc_rotate_v_rotate)
joint_qc_rotate_v_rotate_corr <- do.call(rbind, joint_qc_rotate_v_rotate_norm_corr)
joint_qc_rotate_v_rotate_corr$qc_type <- 'joint'
joint_qc_scale_v_scale_norm_corr <- lapply((final_min+1):(final_max+1), get_correls, comp_table = joint_qc_scale_v_scale)
joint_qc_scale_v_scale_corr <- do.call(rbind, joint_qc_scale_v_scale_norm_corr)
joint_qc_scale_v_scale_corr$qc_type <- 'joint'

scale_v_scale_corr$qc_type <- 'none'
rotate_v_rotate_corr$qc_type <- 'none'
tess_v_tess_corr$qc_type <- 'none'
all_v_all_corr$qc_type <- 'none'

rotate_diff_tess_v_tess_norm_corr <- lapply((final_min+1):(final_max+1), get_correls, comp_table = rotate_diff_tess_v_tess)
rotate_diff_tess_v_tess_corr <- do.call(rbind, rotate_diff_tess_v_tess_norm_corr)
rotate_diff_tess_v_tess_corr$qc_type <- 'rotate_diff'
rotate_diff_all_v_all_norm_corr <- lapply((final_min+1):(final_max+1), get_correls, comp_table = rotate_diff_all_v_all)
rotate_diff_all_v_all_corr <- do.call(rbind, rotate_diff_all_v_all_norm_corr)
rotate_diff_all_v_all_corr$qc_type <- 'rotate_diff'
rotate_diff_rotate_v_rotate_norm_corr <- lapply((final_min+1):(final_max+1), get_correls, comp_table = rotate_diff_rotate_v_rotate)
rotate_diff_rotate_v_rotate_corr <- do.call(rbind, rotate_diff_rotate_v_rotate_norm_corr)
rotate_diff_rotate_v_rotate_corr$qc_type <- 'rotate_diff'
rotate_diff_scale_v_scale_norm_corr <- lapply((final_min+1):(final_max+1), get_correls, comp_table = rotate_diff_scale_v_scale)
rotate_diff_scale_v_scale_corr <- do.call(rbind, rotate_diff_scale_v_scale_norm_corr)
rotate_diff_scale_v_scale_corr$qc_type <- 'rotate_diff'

all_v_all_corr_qc_comp <- rbind(all_v_all_corr, angle_qc_all_v_all_corr, scale_qc_all_v_all_corr, joint_qc_all_v_all_corr, rotate_diff_all_v_all_corr)
all_v_all_corr_qc_comp <- rbind(all_v_all_corr, angle_qc_all_v_all_corr, scale_qc_all_v_all_corr, joint_qc_all_v_all_corr)
scale_v_scale_corr_qc_comp <- rbind(scale_v_scale_corr, angle_qc_scale_v_scale_corr, scale_qc_scale_v_scale_corr, joint_qc_scale_v_scale_corr, rotate_diff_scale_v_scale_corr)
scale_v_scale_corr_qc_comp <- rbind(scale_v_scale_corr, angle_qc_scale_v_scale_corr, scale_qc_scale_v_scale_corr, joint_qc_scale_v_scale_corr)
rotate_v_rotate_corr_qc_comp <- rbind(rotate_v_rotate_corr, angle_qc_rotate_v_rotate_corr, scale_qc_rotate_v_rotate_corr, joint_qc_rotate_v_rotate_corr, rotate_diff_rotate_v_rotate_corr)
rotate_v_rotate_corr_qc_comp <- rbind(rotate_v_rotate_corr, angle_qc_rotate_v_rotate_corr, scale_qc_rotate_v_rotate_corr, joint_qc_rotate_v_rotate_corr)
tess_v_tess_corr_qc_comp <- rbind(tess_v_tess_corr, angle_qc_tess_v_tess_corr, scale_qc_tess_v_tess_corr, joint_qc_tess_v_tess_corr, rotate_diff_tess_v_tess_corr)
tess_v_tess_corr_qc_comp <- rbind(tess_v_tess_corr, angle_qc_tess_v_tess_corr, scale_qc_tess_v_tess_corr, joint_qc_tess_v_tess_corr)

ggplot(all_v_all_corr_qc_comp, aes(correl, fill=qc_type))+ geom_histogram(alpha=0.5, aes(y=..density..), position = "identity")
ggplot(all_v_all_corr_qc_comp, aes(correl, fill=qc_type))+geom_density(alpha=0.2)

ggplot(scale_v_scale_corr_qc_comp, aes(correl, fill=qc_type))+ geom_histogram(alpha=0.5, aes(y=..density..), position = "identity")
ggplot(scale_v_scale_corr_qc_comp, aes(correl, fill=qc_type))+geom_density(alpha=0.2)

ggplot(rotate_v_rotate_corr_qc_comp, aes(correl, fill=qc_type))+ geom_histogram(alpha=0.5, aes(y=..density..), position = "identity")
ggplot(rotate_v_rotate_corr_qc_comp, aes(correl, fill=qc_type))+geom_density(alpha=0.2)

ggplot(tess_v_tess_corr_qc_comp, aes(correl, fill=qc_type))+ geom_histogram(alpha=0.5, aes(y=..density..), position = "identity")
ggplot(tess_v_tess_corr_qc_comp, aes(correl, fill=qc_type))+geom_density(alpha=0.2)


tess_v_tess_corr$type <- 'tess'
tess_v_tess_corr$qc_type <- NULL
scale_qc_scale_v_scale_corr$type <- 'scale'
scale_qc_scale_v_scale_corr$qc_type <- NULL
rotate_diff_rotate_v_rotate_corr$type <- 'rotate'
rotate_diff_rotate_v_rotate_corr$qc_type <- NULL
joint_qc_all_v_all_corr$type <- 'all'
joint_qc_all_v_all_corr$qc_type <- NULL




biggest <- rbind(df_transforms, big_table2, procrustes_big_table)

ggplot(biggest, aes(correl, fill=type))+geom_density(alpha=0.2) + labs(x = 'Correlation', y='Density', colour = 'Transformations' ) +
  facet_grid(.~qc) +
  theme_bw() +
  theme(legend.key.size = unit(0.5, "in")) + 
  theme(legend.text = element_text(size = 12)) + 
  theme(legend.title = element_text(size=12)) +
  theme(strip.text.x = element_text(size = 12)) +
  coord_fixed(ratio = 0.05)



big_table2 <- rbind(tess_v_tess_corr, scale_qc_scale_v_scale_corr, rotate_diff_rotate_v_rotate_corr, joint_qc_all_v_all_corr)
big_table2$qc <- 'Landmark Method with QC'

df_transforms$qc <- 'Landmark Method with No QC'

ggplot(big_table2, aes(correl, fill=type))+ geom_histogram(alpha=0.5, aes(y=..density..), position = "identity")
wt_qc <- ggplot(big_table2, aes(correl, fill=type))+geom_density(alpha=0.2) + + labs(x = 'Correlation', y='Density') 

ggplot(df_transforms, aes(correl, fill=type))+ geom_histogram(alpha=0.5, aes(y=..density..), position = "identity")
ggplot(df_transforms, aes(correl, fill=type))+geom_density(alpha=0.2) + labs(x = 'Correlation', y='Density')

big_table <- rbind(all_v_all_corr_qc_comp, scale_v_scale_corr_qc_comp, rotate_v_rotate_corr_qc_comp, tess_v_tess_corr_qc_comp)

ggplot(big_table, aes(correl, fill=qc_type))+ geom_histogram(alpha=0.5, aes(y=..density..), position = "identity")
ggplot(big_table, aes(correl, fill=qc_type))+geom_density(alpha=0.2)
 #################################################
####################PLOTTING#####################
#################################################

#################plotting correlations of angle corrected######################
###########Plotting scatter plots of correlation vs triangle############
pdf("/Users/currant/OCTeyes/scale_and_rotate_graphs/final_plots_we_hope/per_triangle_mean_norm_correlation_fix.pdf")
plot(anglef_tess_v_tess_corr, xlab="Triangle ID", ylab="Correlation", main="Tesselation vs tesselation per triangle")
plot(anglef_all_v_all_corr, xlab="Triangle ID", ylab="Correlation", main="All vs all per triangle")
plot(anglef_scale_v_scale_corr, xlab="Triangle ID", ylab="Correlation", main="Scale vs scale per triangle")
plot(anglef_rotate_v_rotate_corr, xlab="Triangle ID", ylab="Correlation", main="Rotate vs rotate per triangle")
dev.off()
############PLotting distribution of correlations ############
pdf("/Users/currant/OCTeyes/scale_and_rotate_graphs/final_plots_we_hope/per_triangle_mean_norm_correlation_histogram_fix.pdf")
hist(anglef_tess_v_tess_corr[,2], xlab="Correlation", main="Tesselation vs Tesselation")
hist(anglef_all_v_all_corr[,2], xlab="Correlation", main="All vs All")
hist(anglef_scale_v_scale_corr[,2], xlab="Correlation", main="Scale vs Scale")
hist(anglef_rotate_v_rotate_corr[,2], xlab="Correlation", main="Rotate vs Rotate")
dev.off()

################plotting correlations of scale corrected########################
###########Plotting scatter plots of correlation vs triangle############
pdf("/Users/currant/OCTeyes/scale_and_rotate_graphs/final_plots_we_hope/per_triangle_mean_norm_correlation_fix.pdf")
plot(scalef_tess_v_tess_corr, xlab="Triangle ID", ylab="Correlation", main="Tesselation vs tesselation per triangle")
plot(scalef_all_v_all_corr, xlab="Triangle ID", ylab="Correlation", main="All vs all per triangle")
plot(scalef_scale_v_scale_corr, xlab="Triangle ID", ylab="Correlation", main="Scale vs scale per triangle")
plot(scalef_rotate_v_rotate_corr, xlab="Triangle ID", ylab="Correlation", main="Rotate vs rotate per triangle")
dev.off()
############PLotting distribution of correlations ############
pdf("/Users/currant/OCTeyes/scale_and_rotate_graphs/final_plots_we_hope/per_triangle_mean_norm_correlation_histogram_fix.pdf")
hist(scalef_tess_v_tess_corr[,2], xlab="Correlation", main="Tesselation vs Tesselation")
hist(scalef_all_v_all_corr[,2], xlab="Correlation", main="All vs All")
hist(scalef_scale_v_scale_corr[,2], xlab="Correlation", main="Scale vs Scale")
hist(scalef_rotate_v_rotate_corr[,2], xlab="Correlation", main="Rotate vs Rotate")
dev.off()

#################plotting correlations of angle and scale corrected##############
###########Plotting scatter plots of correlation vs triangle############
pdf("/Users/currant/OCTeyes/scale_and_rotate_graphs/final_plots_we_hope/per_triangle_mean_norm_correlation_fix.pdf")
plot(jointf_tess_v_tess_corr, xlab="Triangle ID", ylab="Correlation", main="Tesselation vs tesselation per triangle")
plot(jointf_all_v_all_corr, xlab="Triangle ID", ylab="Correlation", main="All vs all per triangle")
plot(jointf_scale_v_scale_corr, xlab="Triangle ID", ylab="Correlation", main="Scale vs scale per triangle")
plot(jointf_rotate_v_rotate_corr, xlab="Triangle ID", ylab="Correlation", main="Rotate vs rotate per triangle")
dev.off()
############PLotting distribution of correlations ############
pdf("/Users/currant/OCTeyes/scale_and_rotate_graphs/final_plots_we_hope/per_triangle_mean_norm_correlation_histogram_fix.pdf")
hist(jointf_tess_v_tess_corr[,2], xlab="Correlation", main="Tesselation vs Tesselation")
hist(jointf_all_v_all_corr[,2], xlab="Correlation", main="All vs All")
hist(jointf_scale_v_scale_corr[,2], xlab="Correlation", main="Scale vs Scale")
hist(jointf_rotate_v_rotate_corr[,2], xlab="Correlation", main="Rotate vs Rotate")
dev.off()



###################################################################################################################################################
###################################################################################################################################################
evens_test_band <- lapply(1:dim(all_params_even)[1], function(x){
  image_file <- all_params_even[[x,1]]
  fovea_height <- all_params_even[[x,5]]
  fovea_coordx <- all_params_even[[x,3]]
  fovea_coordy <- all_params_even[[x,4]]
  fovea_coords <- c(fovea_coordy, fovea_coordx)
  outputz <- test_both(image_file)
  return(outputz)
})
evens_test_band_table <- do.call(rbind, evens_test_band)
quality_keep_even <- which(evens_test_band_table[,1]==1 & evens_test_band_table[,2]==1)


odds_test_band <- lapply(1:dim(all_params_odd)[1], function(x){
  image_file <- all_params_odd[[x,1]]
  fovea_height <- all_params_odd[[x,5]]
  fovea_coordx <- all_params_odd[[x,3]]
  fovea_coordy <- all_params_odd[[x,4]]
  fovea_coords <- c(fovea_coordy, fovea_coordx)
  outputz <- test_both(image_file)
  return(outputz)
})
odds_test_band_table <- do.call(rbind, odds_test_band)
quality_keep_odd <- which(odds_test_band_table[,1]==1 & odds_test_band_table[,2]==1)

quality_keep_joint <- intersect(quality_keep_even, quality_keep_odd)







